version: '3'

networks:
  default-ext:
    external: true

services:
  app:
    stdin_open: true
    tty: true
    build: .
    environment:
      - FLASK_APP=app/api.py
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - default-ext
