version: '3'

networks:
  default-ext:
    external: true

services:
  app:
    stdin_open: true
    tty: true
    build: .
    # command:
    #     - "/bin/bash"
    #     - "-l"
    #     - "-c"
    #     - "yarn install && npm run debug"
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - default-ext
